# coding: utf-8

"""
    The Bisq API

    API for the bisq exchange

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.account_list import AccountList


class TestAccountList(unittest.TestCase):
    """ AccountList unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountList(self):
        """
        Test AccountList
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.account_list.AccountList()
        pass


if __name__ == '__main__':
    unittest.main()
