<?php
/**
 * OfferDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The Bisq API
 *
 * API for the bisq exchange
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OfferDetailTest Class Doc Comment
 *
 * @category    Class */
// * @description OfferDetail
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OfferDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OfferDetail"
     */
    public function testOfferDetail()
    {
    }

    /**
     * Test attribute "offer_id"
     */
    public function testPropertyOfferId()
    {
    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "arbitrators"
     */
    public function testPropertyArbitrators()
    {
    }

    /**
     * Test attribute "offerer"
     */
    public function testPropertyOfferer()
    {
    }

    /**
     * Test attribute "btc_amount"
     */
    public function testPropertyBtcAmount()
    {
    }

    /**
     * Test attribute "min_btc_amount"
     */
    public function testPropertyMinBtcAmount()
    {
    }

    /**
     * Test attribute "other_amount"
     */
    public function testPropertyOtherAmount()
    {
    }

    /**
     * Test attribute "other_currency"
     */
    public function testPropertyOtherCurrency()
    {
    }

    /**
     * Test attribute "price_detail"
     */
    public function testPropertyPriceDetail()
    {
    }
}
