<?php
/**
 * BisqApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The Bisq API
 *
 * API for the bisq exchange
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * BisqApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BisqApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountList
     *
     * .
     *
     */
    public function testAccountList()
    {
    }

    /**
     * Test case for currencyList
     *
     * .
     *
     */
    public function testCurrencyList()
    {
    }

    /**
     * Test case for marketList
     *
     * .
     *
     */
    public function testMarketList()
    {
    }

    /**
     * Test case for moveFundsToBisqWallet
     *
     * .
     *
     */
    public function testMoveFundsToBisqWallet()
    {
    }

    /**
     * Test case for offerCancel
     *
     * .
     *
     */
    public function testOfferCancel()
    {
    }

    /**
     * Test case for offerDetail
     *
     * .
     *
     */
    public function testOfferDetail()
    {
    }

    /**
     * Test case for offerList
     *
     * .
     *
     */
    public function testOfferList()
    {
    }

    /**
     * Test case for offerMake
     *
     * .
     *
     */
    public function testOfferMake()
    {
    }

    /**
     * Test case for offerTake
     *
     * .
     *
     */
    public function testOfferTake()
    {
    }

    /**
     * Test case for paymentReceived
     *
     * .
     *
     */
    public function testPaymentReceived()
    {
    }

    /**
     * Test case for paymentStarted
     *
     * .
     *
     */
    public function testPaymentStarted()
    {
    }

    /**
     * Test case for tradeDetail
     *
     * .
     *
     */
    public function testTradeDetail()
    {
    }

    /**
     * Test case for tradeList
     *
     * .
     *
     */
    public function testTradeList()
    {
    }

    /**
     * Test case for walletAddresses
     *
     * .
     *
     */
    public function testWalletAddresses()
    {
    }

    /**
     * Test case for walletDetail
     *
     * .
     *
     */
    public function testWalletDetail()
    {
    }

    /**
     * Test case for walletTransactionList
     *
     * .
     *
     */
    public function testWalletTransactionList()
    {
    }
}
