/* 
 * The Bisq API
 *
 * API for the bisq exchange
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PriceDetail struct {

	UseMarketPrice bool `json:"use_market_price,omitempty"`

	MarketPriceMargin float64 `json:"market_price_margin,omitempty"`
}
