/* 
 * The Bisq API
 *
 * API for the bisq exchange
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type WalletDetails struct {

	AvailableBalance string `json:"available_balance,omitempty"`

	ReservedBalance string `json:"reserved_balance,omitempty"`

	LockedBalance string `json:"locked_balance,omitempty"`
}
