/*
 * The Bisq API
 * API for the bisq exchange
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ContractData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Account
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-28T16:38:11.248+02:00")
public class Account {
  @SerializedName("payment_account_id")
  private String paymentAccountId = null;

  @SerializedName("created")
  private Long created = null;

  @SerializedName("account_name")
  private String accountName = null;

  @SerializedName("trade_currencies")
  private List<String> tradeCurrencies = null;

  @SerializedName("paymentAccountPayload")
  private String paymentAccountPayload = null;

  @SerializedName("payment_method_details")
  private ContractData paymentMethodDetails = null;

  public Account paymentAccountId(String paymentAccountId) {
    this.paymentAccountId = paymentAccountId;
    return this;
  }

   /**
   * Get paymentAccountId
   * @return paymentAccountId
  **/
  @ApiModelProperty(value = "")
  public String getPaymentAccountId() {
    return paymentAccountId;
  }

  public void setPaymentAccountId(String paymentAccountId) {
    this.paymentAccountId = paymentAccountId;
  }

  public Account created(Long created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public Long getCreated() {
    return created;
  }

  public void setCreated(Long created) {
    this.created = created;
  }

  public Account accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @ApiModelProperty(value = "")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public Account tradeCurrencies(List<String> tradeCurrencies) {
    this.tradeCurrencies = tradeCurrencies;
    return this;
  }

  public Account addTradeCurrenciesItem(String tradeCurrenciesItem) {
    if (this.tradeCurrencies == null) {
      this.tradeCurrencies = new ArrayList<String>();
    }
    this.tradeCurrencies.add(tradeCurrenciesItem);
    return this;
  }

   /**
   * Get tradeCurrencies
   * @return tradeCurrencies
  **/
  @ApiModelProperty(value = "")
  public List<String> getTradeCurrencies() {
    return tradeCurrencies;
  }

  public void setTradeCurrencies(List<String> tradeCurrencies) {
    this.tradeCurrencies = tradeCurrencies;
  }

  public Account paymentAccountPayload(String paymentAccountPayload) {
    this.paymentAccountPayload = paymentAccountPayload;
    return this;
  }

   /**
   * Get paymentAccountPayload
   * @return paymentAccountPayload
  **/
  @ApiModelProperty(value = "")
  public String getPaymentAccountPayload() {
    return paymentAccountPayload;
  }

  public void setPaymentAccountPayload(String paymentAccountPayload) {
    this.paymentAccountPayload = paymentAccountPayload;
  }

  public Account paymentMethodDetails(ContractData paymentMethodDetails) {
    this.paymentMethodDetails = paymentMethodDetails;
    return this;
  }

   /**
   * Get paymentMethodDetails
   * @return paymentMethodDetails
  **/
  @ApiModelProperty(value = "")
  public ContractData getPaymentMethodDetails() {
    return paymentMethodDetails;
  }

  public void setPaymentMethodDetails(ContractData paymentMethodDetails) {
    this.paymentMethodDetails = paymentMethodDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.paymentAccountId, account.paymentAccountId) &&
        Objects.equals(this.created, account.created) &&
        Objects.equals(this.accountName, account.accountName) &&
        Objects.equals(this.tradeCurrencies, account.tradeCurrencies) &&
        Objects.equals(this.paymentAccountPayload, account.paymentAccountPayload) &&
        Objects.equals(this.paymentMethodDetails, account.paymentMethodDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentAccountId, created, accountName, tradeCurrencies, paymentAccountPayload, paymentMethodDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");
    
    sb.append("    paymentAccountId: ").append(toIndentedString(paymentAccountId)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    tradeCurrencies: ").append(toIndentedString(tradeCurrencies)).append("\n");
    sb.append("    paymentAccountPayload: ").append(toIndentedString(paymentAccountPayload)).append("\n");
    sb.append("    paymentMethodDetails: ").append(toIndentedString(paymentMethodDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

